### ISSUE TITLE
Save blended metadata 

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-forecast-blend#15]
## Detailed Description
Would be great to save what models and weights are used for each forecast

## Context
- good to know where the values come from

## Possible Implementation
1.  add to 'plevel' column in `nowcasting_datamodel`
2. Get forecasts to save to both `plevel` and `properties`.
3. Update blend service to use `plevel` column, but save to both
4. Get forecasts to only save to `plevel`
5. Update api to read `plevel` column
6. Update blend service to save the weights used for each model in the `properties` column

**Comment by aryanbhosale** [comment]
Hi @peterdudfield , does [nowcasting-datamodel](https://github.com/openclimatefix/nowcasting_datamodel) need to be updated for this issue?

**Comment by peterdudfield** [comment]
yea this should be in `nowcasting_datamodel`

**Comment by peterdudfield** [comment]
I think ill just close this for the moment, as we dont plan to do it
